version: 2.1

orbs:
  frontend-tools: contentful/frontend-tools@2
  vault: contentful/vault@1.30.0

executors:
  default:
    docker:
      - image: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

cache-key: &cache-key
  key: v2-npm-cache-{{ arch }}-{{ checksum ".nvmrc" }}-{{ checksum "pnpm-lock.yaml" }}-{{ .Branch }}

commands:
  setup_pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            npm install --global corepack@latest
            corepack enable
            corepack prepare pnpm --activate
            pnpm config set store-dir .pnpm-store

  pnpm_install:
    steps:
      - restore_cache: *cache-key
      - run: node -v
      - run: pnpm -v
      - run: pnpm install --frozen-lockfile --prefer-offline
      - save_cache:
          <<: *cache-key
          paths:
            - .pnpm-store

jobs:
  lint-and-test:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: packages-read
      - setup_pnpm
      - pnpm_install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm prettier:check
      - run: pnpm test
      - store_test_results:
          path: reports
    resource_class: medium+

  release:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: semantic-release
      - run: git config --global user.email $GIT_COMMITTER_EMAIL
      - run: git config --global user.name $GIT_COMMITTER_NAME
      - run: git remote set-url origin "https://$GIT_AUTHOR_NAME:$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - setup_pnpm
      - pnpm_install
      - run: pnpm build
      - run: pnpm lerna version --no-private --conventional-commits --create-release github --yes
      - run: pnpm lerna publish from-git --yes

  compressed-size:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: packages-read
      - vault/get-secrets:
          template-preset: github-comment
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_READ_TOKEN}" > ~/.npmrc
      - run: echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - frontend-tools/compressed-size:
          package-manager: pnpm

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - lint-and-test:
          context:
            - vault
      - release:
          context:
            - vault
          filters:
            branches:
              only: master
          requires:
            - lint-and-test
  compressed-size:
    jobs:
      - compressed-size:
          context:
            - vault
