version: 2.1

orbs:
  frontend-tools: contentful/frontend-tools@2
  vault: contentful/vault@1.30.0
  nx: nrwl/nx@1.6.2

executors:
  default:
    docker:
      - image: cimg/node:24.13.1

cache-key: &cache-key
  key: v2-npm-cache-{{ arch }}-{{ checksum ".nvmrc" }}-{{ checksum "pnpm-lock.yaml" }}-{{ .Branch }}

commands:
  setup_pnpm:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            corepack prepare pnpm --activate
            pnpm config set store-dir .pnpm-store

  pnpm_install:
    steps:
      - restore_cache: *cache-key
      - run: node -v
      - run: pnpm -v
      - run: pnpm install --frozen-lockfile --prefer-offline
      - save_cache:
          <<: *cache-key
          paths:
            - .pnpm-store

  nx_set_shas:
    steps:
      - vault/get-secrets:
          template-preset: nx-read-circleci
      - nx/set-shas:
          error-on-no-successful-workflow: true
          main-branch-name: master

jobs:
  lint-and-test:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: packages-read
      - setup_pnpm
      - pnpm_install
      - nx_set_shas
      - run: pnpm exec nx affected --target=build --base=$NX_BASE --head=$NX_HEAD
      - run: pnpm exec nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD
      - run: pnpm exec nx affected --target=prettier:check --base=$NX_BASE --head=$NX_HEAD
      - run: pnpm exec nx affected --target=test --base=$NX_BASE --head=$NX_HEAD
      - store_test_results:
          path: reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
    resource_class: medium+


  release:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: semantic-release
      - attach_workspace:
          at: ~/project
      - vault/configure-lerna
      - run: |
          echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_WRITE_TOKEN}" >> ~/.npmrc
      - run: pnpm nx run-many -t build
      - run: pnpm lerna version --no-private --conventional-commits --create-release github --yes
      - run: pnpm lerna publish from-git --yes

  compressed-size:
    executor: default
    steps:
      - checkout
      - vault/get-secrets:
          template-preset: packages-read
      - vault/get-secrets:
          template-preset: github-comment
      - run: |
          echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_READ_TOKEN}" >> ~/.npmrc
      - frontend-tools/compressed-size:
          package-manager: pnpm

workflows:
  version: 2
  # run on every commit
  commit:
    jobs:
      - lint-and-test:
          context:
            - vault
      - release:
          context:
            - vault
          filters:
            branches:
              only: master
          requires:
            - lint-and-test
  compressed-size:
    jobs:
      - compressed-size:
          context:
            - vault
